name: PHP Tests

on: ['push', 'pull_request']

jobs:
  test:
    name: 'PHP ${{ matrix.php-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3
      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: none
      - name: Run Tests
        run:  make php
  check:
    name: 'Check Format & Types'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: x64
    - name: Install dependencies
      run: make pydeps
    - name: Check & Lint Python
      run: make pycheck