name: Python Tests

on: ['push', 'pull_request']

jobs:
  test:
    name: 'Test Python ${{ matrix.python-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy3.9', 'pypy3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: make python
  check:
    name: 'Check Format & Types'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: x64
    - name: Install dependencies
      run: make pydeps
    - name: Check & Lint Python
      run: make pycheck
